server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
  instance:
    hostname: 192.168.1.111
spring:
  application:
    name: eureka